/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jib_dev_env_gradle_template;

public class App {
    public String getGreeting() {
        return "Jib Env: It worked";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
